### ISSUE TITLE
How to record and save the captured audio on WAV file?

### ISSUE THREAD

**Issue by dev-bre** [nsglover/OpenAL.NETCore#1]
Hi,
Can you please provide some kind of sample code about how to use this library?

The sample project doesn't really help to understand how to use your library.

Do you supporting recording and save to WAV cross-platform?

**Comment by nsglover** [comment]
Yeah, I got pretty lazy about making samples. My apologies; didn't expect people to actually use this project. I'm currently in school and too busy to do much, but I can tell you that I support anything supported by OpenAL-soft 1.1. These are just C# bindings that I've written, so there's essentially no features provided on my end; if you want to learn how to record and save WAVs, just look up how to do it with OpenAL. All functions in my library have the same names and specifications as they do in the OpenAL specification, so if you need to know how to do anything with my library, just find how to do it with normal OpenAL and use the corresponding binding functions. Any "get started with OpenAL" tutorial should suffice.
